/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bon.achat;

import static bon.achat.Authentification.numservice;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Administrator
 */
public class Ban_achats extends javax.swing.JFrame {
     Connection conx=null;
    PreparedStatement prepared=null;
    ResultSet result=null,result1=null;
    String code,nom,specialit,req1="" ,req="",numero="",nom_service,code_service,dateachat,articles;
     
    public Ban_achats() {
        initComponents();
        conx=connecter.connecterDB();
        
        req="select nom_article from `article`";
         try {
               prepared=conx.prepareStatement(req);
               result=prepared.executeQuery();
               while(result.next())
               {
                   jComboBox_Article.addItem(result.getString("nom_article"));
               }
         } catch (SQLException ex) {
             Logger.getLogger(Ban_achats.class.getName()).log(Level.SEVERE, null, ex);
         }
         
        req1="select nom_service from service where num_service=? ";
         try {
             prepared=conx.prepareStatement(req1);
             prepared.setString(1, numservice);
             result1=prepared.executeQuery();
             while(result1.next())
             {
                 nom=result1.getString("nom_service");
             }
             
             jTextField_service.setText(nom);
         } catch (SQLException ex) {
             Logger.getLogger(Ban_achats.class.getName()).log(Level.SEVERE, null, ex);
         }
        
        
        jComboBox_Article.setSelectedIndex(-1);
        jTextField_service.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_Qte = new javax.swing.JTextField();
        jComboBox_Article = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField_service = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_observation = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1029, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel1.setText("Nom article :");

        jLabel2.setText("Service :");

        jLabel3.setText("Date livraison :");

        jLabel4.setText("Quantite :");

        jTextField_Qte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_QteKeyTyped(evt);
            }
        });

        jDateChooser1.setDateFormatString("yyyy-MM-dd");

        jButton1.setText("Inserer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Modifier");

        jButton3.setText("Imprimer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel6.setText("Observations :");

        jTextArea_observation.setColumns(20);
        jTextArea_observation.setRows(5);
        jScrollPane2.setViewportView(jTextArea_observation);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox_Article, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField_service)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                .addComponent(jTextField_Qte))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(41, 41, 41)
                        .addComponent(jButton3)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox_Article, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_service, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Qte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton5.setText("Afficher");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addComponent(jButton5)
                .addContainerGap())
        );

        jLabel5.setText("Recherche par ");

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jDateChooser2.setDateFormatString("yyyy-MM-dd");
        jDateChooser2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jDateChooser2KeyReleased(evt);
            }
        });

        jButton4.setText("Afficher");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(293, 293, 293))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(jButton4)
                        .addGap(156, 156, 156))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4))
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 9, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      SimpleDateFormat dateFormat=new SimpleDateFormat("yyyy-MM-dd");
            String date = dateFormat.format(jDateChooser2.getDate());
        req="SELECT code_service,nom_service,date_achat,nom_article,qte_demande FROM article inner join achat ON article.code_article=achat.code_article INNER join service on service.num_service=achat.num_service WHERE date_achat LIKE '"+date+"%'";
        try {
            
             prepared=conx.prepareStatement(req);
             result=prepared.executeQuery();
             jTable1.setModel(DbUtils.resultSetToTableModel(result));
             
             
         } catch (SQLException ex) {
             
            JOptionPane.showMessageDialog(null,"la connection n'exist pas veuiller l'activer a l'aide de l'application wampserveur ", "Error", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(Service.class.getName()).log(Level.SEVERE, null, ex);
         }
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    public void Afficher_table() {
       req="SELECT code_service,nom_service,date_achat,nom_article,qte_demande FROM article inner join achat ON article.code_article=achat.code_article INNER join service on service.num_service=achat.num_service ";
        try {
            
             prepared=conx.prepareStatement(req);
             result=prepared.executeQuery();
             jTable1.setModel(DbUtils.resultSetToTableModel(result));
             
             
         } catch (SQLException ex) {
             
            JOptionPane.showMessageDialog(null,"la connection n'exist pas veuiller l'activer a l'aide de l'application wampserveur ", "Error", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(Service.class.getName()).log(Level.SEVERE, null, ex);
         }
      
    }
        
    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if(jTextField_Qte.getText().trim().equals("") || jComboBox_Article.getSelectedIndex()==-1||jDateChooser1.getDate()==null)
        {
            JOptionPane.showMessageDialog(null,"veuillez remplir les cases qui sont vide");

        }else {
            result=null;
            SimpleDateFormat dateFormat=new SimpleDateFormat("yyyy-MM-dd");
            String date = dateFormat.format(jDateChooser1.getDate());

            req1="select code_article from `article` where nom_article=?";
            try {
                prepared=conx.prepareStatement(req1);
                prepared.setString(1, jComboBox_Article.getSelectedItem().toString());
                result=prepared.executeQuery();
                while(result.next())
                {
                    code=result.getString("code_article");
                }
            } catch (SQLException ex) {
                Afficher_table();
                Logger.getLogger(Ban_achats.class.getName()).log(Level.SEVERE, null, ex);
            }

            try {
                req="insert into `achat`(`Qte_demande`, `date_achat`, `code_article`, `num_service`) values(?,?,?,?)";
                prepared=conx.prepareStatement(req);
                prepared.setString(1, jTextField_Qte.getText());
                prepared.setString(2,date);
                prepared.setString(3, code);
                prepared.setString(4, numservice);
                prepared.execute();
                JOptionPane.showMessageDialog(null,"Service est ajoutè avec succès");

            } catch (SQLException ex) {

                JOptionPane.showMessageDialog(null,"Duplication du code service il est unique ou la connection n'exist plus veuiller l'activer a l'aide de l'application wampserveur", "Error", JOptionPane.ERROR_MESSAGE);
                Afficher_table();
                Logger.getLogger(Service.class.getName()).log(Level.SEVERE, null, ex);
            }
            Afficher_table();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField_QteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_QteKeyTyped

        char vChar = evt.getKeyChar();
        if (!(Character.isDigit(vChar) || (vChar == KeyEvent.VK_BACK_SPACE) || (vChar == KeyEvent.VK_DELETE)))
        { evt.consume(); }
    }//GEN-LAST:event_jTextField_QteKeyTyped

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
         
        
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jDateChooser2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDateChooser2KeyReleased
        SimpleDateFormat dateFormat=new SimpleDateFormat("yyyy-MM-dd");
            String date = dateFormat.format(jDateChooser1.getDate());
        
        
        
        req="SELECT code_service,nom_service,date_achat,nom_article,qte_demande FROM article inner join achat ON article.code_article=achat.code_article INNER join service on service.num_service=achat.num_service WHERE date_achat LIKE '"+date+"%'";
        try {
            prepared=conx.prepareStatement(req);
            result=prepared.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(result));

        } catch (SQLException ex) {
            Logger.getLogger(Categories.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jDateChooser2KeyReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Afficher_table();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
        Document doc=new Document();
         try {
              SimpleDateFormat dateFormat=new SimpleDateFormat("yyyy-MM-dd");
              String date = dateFormat.format(jDateChooser2.getDate());
              //req="SELECT code_service,nom_service,date_achat,nom_article,qte_demande FROM article inner join achat ON article.code_article=achat.code_article INNER join service on service.num_service=achat.num_service WHERE date_achat LIKE '"+date+"%'";
              req="SELECT code_service,nom_service,date_achat,nom_article,qte_demande FROM article inner join achat ON article.code_article=achat.code_article INNER join service on service.num_service=achat.num_service WHERE date_achat LIKE '"+date+"%' and nom_service='"+jTextField_service.getText()+"'";
       
             prepared=conx.prepareStatement(req);
             result=prepared.executeQuery();
             PdfWriter.getInstance(doc, new FileOutputStream("C:\\Users\\Administrator\\Desktop\\achat.pdf"));
             doc.open();
             Image img=Image.getInstance("C:\\Users\\Administrator\\Documents\\GitHub\\Stage_ONDA\\Gestion d'achat\\Bon achat\\src\\ondia.PNG");
             img.scaleAbsoluteWidth(600);
             img.scaleAbsoluteHeight(170);
             img.setAlignment(Image.ALIGN_CENTER);
             doc.add(img);
             PdfPTable table=new PdfPTable(7);
             table.setWidthPercentage(100);
             table.setHorizontalAlignment(200);
             PdfPCell cell;
             /////////
             cell=new PdfPCell(new Phrase("Demandeur",FontFactory.getFont("Tahoma",12)));
             cell.setHorizontalAlignment(Element.ALIGN_CENTER);
             table.addCell(cell);
             
             cell=new PdfPCell(new Phrase("Code de service",FontFactory.getFont("Tahoma",12)));
             cell.setHorizontalAlignment(Element.ALIGN_CENTER);
             table.addCell(cell);
             
             cell=new PdfPCell(new Phrase("Date",FontFactory.getFont("Tahoma",12)));
             cell.setHorizontalAlignment(Element.ALIGN_CENTER);
             table.addCell(cell);
             
             cell=new PdfPCell(new Phrase("Magasin livreur",FontFactory.getFont("Tahoma",12)));
             cell.setHorizontalAlignment(Element.ALIGN_CENTER);
             cell.setColspan(2);
             table.addCell(cell);
             
             cell=new PdfPCell(new Phrase("Code magasinn",FontFactory.getFont("Tahoma",12)));
             cell.setHorizontalAlignment(Element.ALIGN_CENTER);
             cell.setColspan(2);
             table.addCell(cell);
             //ligne 2
             
             cell=new PdfPCell(new Phrase(" ",FontFactory.getFont("Tahoma",12)));
             cell.setHorizontalAlignment(Element.ALIGN_CENTER);
             table.addCell(cell);
             
             cell=new PdfPCell(new Phrase(" ",FontFactory.getFont("Tahoma",12)));
             cell.setHorizontalAlignment(Element.ALIGN_CENTER);
             table.addCell(cell);
             
             cell=new PdfPCell(new Phrase(" ",FontFactory.getFont("Tahoma",12)));
             cell.setHorizontalAlignment(Element.ALIGN_CENTER);
             table.addCell(cell);
             
             cell=new PdfPCell(new Phrase(" ",FontFactory.getFont("Tahoma",12)));
             cell.setHorizontalAlignment(Element.ALIGN_CENTER);
             cell.setColspan(2);
             table.addCell(cell);
             
             cell=new PdfPCell(new Phrase(" ",FontFactory.getFont("Tahoma",12)));
             cell.setHorizontalAlignment(Element.ALIGN_CENTER);
             cell.setColspan(2);
             table.addCell(cell);
             
        
             ///ligne3
             cell=new PdfPCell(new Phrase("Articles",FontFactory.getFont("Tahoma",12)));
             cell.setHorizontalAlignment(Element.ALIGN_CENTER);
             cell.setColspan(2);
             table.addCell(cell);
             
             cell=new PdfPCell(new Phrase("Quantite demandee",FontFactory.getFont("Tahoma",12)));
             cell.setHorizontalAlignment(Element.ALIGN_CENTER);
             table.addCell(cell);
             
             cell=new PdfPCell(new Phrase("Quantite livraiee",FontFactory.getFont("Tahoma",12)));
             cell.setHorizontalAlignment(Element.ALIGN_CENTER);
             table.addCell(cell);
             
             cell=new PdfPCell(new Phrase("Code centre",FontFactory.getFont("Tahoma",12)));
             cell.setHorizontalAlignment(Element.ALIGN_CENTER);
             
             table.addCell(cell);
             
             cell=new PdfPCell(new Phrase("Rubrique",FontFactory.getFont("Tahoma",12)));
             cell.setHorizontalAlignment(Element.ALIGN_CENTER);
             table.addCell(cell);
             
             cell=new PdfPCell(new Phrase("Estimation",FontFactory.getFont("Tahoma",12)));
             cell.setHorizontalAlignment(Element.ALIGN_CENTER);
             table.addCell(cell);
            ////
             ///ligne4
            while(result.next()){
             cell=new PdfPCell(new Phrase("-"+result.getString("nom_article"),FontFactory.getFont("Tahoma",12)));
             cell.setColspan(2);
             table.addCell(cell);
             
             cell=new PdfPCell(new Phrase(result.getString("qte_demande"),FontFactory.getFont("Tahoma",12)));
             cell.setHorizontalAlignment(Element.ALIGN_CENTER);
             table.addCell(cell);
             
             cell=new PdfPCell(new Phrase(" ",FontFactory.getFont("Tahoma",12)));
             cell.setHorizontalAlignment(Element.ALIGN_CENTER);
             table.addCell(cell);
             
             cell=new PdfPCell(new Phrase(" ",FontFactory.getFont("Tahoma",12)));
             cell.setHorizontalAlignment(Element.ALIGN_CENTER);
             
             table.addCell(cell);
             
             cell=new PdfPCell(new Phrase(" ",FontFactory.getFont("Tahoma",12)));
             cell.setHorizontalAlignment(Element.ALIGN_CENTER);
             table.addCell(cell);
             
             cell=new PdfPCell(new Phrase(" ",FontFactory.getFont("Tahoma",12)));
             cell.setHorizontalAlignment(Element.ALIGN_CENTER);
             table.addCell(cell);
            }
             ///ligne5 observation
             cell=new PdfPCell(new Phrase("Observations : "+jTextArea_observation.getText()+"\n\n",FontFactory.getFont("Tahoma",12)));
             cell.setColspan(7);
             table.addCell(cell);
             //////
             /////ligne6
             cell=new PdfPCell(new Phrase("Exemplaire",FontFactory.getFont("Tahoma",12)));
             cell.setHorizontalAlignment(Element.ALIGN_CENTER);
             table.addCell(cell);
             
             cell=new PdfPCell(new Phrase("signature service demandeur",FontFactory.getFont("Tahoma",12)));
             cell.setHorizontalAlignment(Element.ALIGN_CENTER);
             cell.setColspan(2);
             table.addCell(cell);
             
             cell=new PdfPCell(new Phrase("Unite de stockage",FontFactory.getFont("Tahoma",12)));
             cell.setHorizontalAlignment(Element.ALIGN_CENTER);
             cell.setColspan(2);
             table.addCell(cell);
             
             cell=new PdfPCell(new Phrase("Controle",FontFactory.getFont("Tahoma",12)));
             cell.setHorizontalAlignment(Element.ALIGN_CENTER);
             cell.setColspan(2);
             table.addCell(cell);
             ////
               /////ligne7
               
             cell=new PdfPCell(new Phrase("\n\n\n\n\n\n\n\n\n",FontFactory.getFont("Tahoma",12)));
             cell.setHorizontalAlignment(Element.ALIGN_CENTER);
             table.addCell(cell);
             
             cell=new PdfPCell(new Phrase("\n\n\n\n\n\n\n\n\n",FontFactory.getFont("Tahoma",12)));
             cell.setHorizontalAlignment(Element.ALIGN_CENTER);
             cell.setColspan(2);
             table.addCell(cell);
             
             cell=new PdfPCell(new Phrase("\n\n\n\n\n\n\n\n\n",FontFactory.getFont("Tahoma",12)));
             cell.setHorizontalAlignment(Element.ALIGN_CENTER);
             cell.setColspan(2);
             table.addCell(cell);
             
             cell=new PdfPCell(new Phrase("",FontFactory.getFont("Tahoma",12)));
             cell.setHorizontalAlignment(Element.ALIGN_CENTER);
             cell.setColspan(2);
             table.addCell(cell);
             ////
             
             
             
             doc.add(table);
             doc.close();
             Desktop.getDesktop().open(new File("C:\\Users\\Administrator\\Desktop\\achat.pdf"));
         } catch (FileNotFoundException ex) {
             JOptionPane.showConfirmDialog(null, "ma khdamch tablo");
             Logger.getLogger(Ban_achats.class.getName()).log(Level.SEVERE, null, ex);
         } catch (DocumentException ex) {
             JOptionPane.showConfirmDialog(null, "ma khdamch tablo");
             Logger.getLogger(Ban_achats.class.getName()).log(Level.SEVERE, null, ex);
         } catch (IOException ex) {
             JOptionPane.showConfirmDialog(null, "ma khdamch tablo");
             Logger.getLogger(Ban_achats.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Ban_achats.class.getName()).log(Level.SEVERE, null, ex);
         }
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ban_achats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ban_achats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ban_achats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ban_achats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ban_achats().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox_Article;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea_observation;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField_Qte;
    private javax.swing.JTextField jTextField_service;
    // End of variables declaration//GEN-END:variables
}
